### ISSUE TITLE
Using official PostgREST docker container

### ISSUE THREAD

**Issue by begriffs** [erasche/docker-recipes#1]
Hey @erasche today I created an official postgrest repo on dockerhub: https://hub.docker.com/r/begriffs/postgrest/

Wondered if you could try basing your image off that one rather than `biscarch/postgrest`? The more people use it the more we'll work out bugs and the better I can support it.

**Comment by hexylena** [comment]
Hey @begriffs, absolutely happy to! I'll get that switched over next week.

**Comment by begriffs** [comment]
Just checking in, have you made the switch?

**Comment by hexylena** [comment]
@begriffs sure haven't, sorry. Work has been hellish fighting other fires. I'll ping you when I get to this! Promise!

**Comment by hexylena** [comment]
Sorry that took absolutely forever @begriffs. Switched to your image, everything looks fine for my end. Thanks for building postgrest, it's really an amazing tool.
